name: Deploy to VPS

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger VPS Deploy Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME || 'root' }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /var/www/polaryon
            git fetch origin main
            git reset --hard origin/main
            bash -l vps-deploy.sh
